name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Defaults
        run: ./defaults.sh
      - name: Install Software
        run: ./install.sh
      - name: Run ShellCheck
        run: |
          brew install shellcheck
          shellcheck *.sh
